<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MailFlow.DataAccess\MailFlow.DataAccess.csproj" />
    <ProjectReference Include="..\MailFlow.Entities\MailFlow.Entities.csproj" />
  </ItemGroup>

</Project>
