<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>d61750e2-cd48-4ffc-a605-62f03cab6560</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\EmailCreator.Business\EmailCreator.Business.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="11.9.0" />
    <PackageReference Include="Google.Apis.Auth.AspNetCore3" Version="1.76.0" />
    <PackageReference Include="Google.Apis.Gmail.v1" Version="1.75.0.4225" />
  </ItemGroup>

</Project>
